end/demo001/bookdemo/bookdemo/urls.py
from django.contrib import admin
from django.urls import path, include

'''
路由地址配置
每一个网址绑定一个视图函数，视图函数返回页面
MVT T视图 作用： 接受请求  处理数据 返回响应
总的路由配置文件 == 项目路由文件 使用include包含
'''

urlpatterns = [
    path('admin/', admin.site.urls),
    path('publish/', include('publish.urls', namespace='publish')),
    path('', include('booktest.urls', namespace='booktest')),


]

end/demo001/bookdemo/publish/urls.py
# ProjectName:Ldemo001
# FileName:urls
# author:asus
# datetime:2020/2/17 10:14
# software: PyCharm
from django.conf.urls import url
from . import views

app_name = 'publish'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # url(r'^detail/(\d+)/$', views.detail, name='detail'),

    url(r'^detail/(?P<qid>\d+)/$', views.detail, name='detail'),
    url(r'^result/(\d+)/$', views.result, name='result'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^regist/$', views.regist, name='regist')

    # url(r'^$',views.IndexView.as_view(),name='index'),
    # url(r'^detail/(?P<qid>\d+)/$',views.DetailView.as_view(),name='detail'),
    # url(r'^result/(\d+)/$',views.ResultView.as_view(),name='result')

]

end/demo001/bookdemo/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            投票应用
        {% endblock%}
    </title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
<div class="container">
    {% block header %}
    <div>
        {% if request.user and request.user.username != '' %}
        用户名： {{ request.user}} <a href="{% url 'publish:logout' %}">退出</a>
        {% else %}
        <a href="{% url 'publish:login' %}">登录</a> <a href="{% url 'publish:regist' %}">注册</a>
        {% endif%}

    </div>

    {% endblock %}

    {% block body %}
    身体
    {% endblock %}

    {% block footer%}
<!--     <div class="pict">-->
<!--&lt;!&ndash;        <iframe src="/static/img/afc.jpg" frameborder="0"></iframe>&ndash;&gt;-->
<!--        <img src="/static/img/afc.jpg" alt="" style="width: 300px;height: 170px">-->
<!--     </div>-->
    {% endblock %}


</div>
</body>
</html>

end/demo001/bookdemo/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block title %}
 投票选择
{% endblock%}
{% block body%}
<div style="width: 500px;margin: 0 auto;">


    <h2> 投票的问题是： {{question.title}} </h2>
    <ul>
        <h3>选项有</h3>
        <form action="#" method="post">
            {% csrf_token %}
            {% for c in question.choices.all %}
            {% if forloop.counter == 1 %}
            <li><input type="radio" checked name="num" value="{{c.id}}"> {{c.content}}</li>
            {% else %}
            <li><input type="radio" name="num" value="{{c.id}}"> {{c.content}}</li>
            {% endif %}
            {% endfor %}
            <input type="submit" value="投票">
        </form>
    </ul>
    <br>
    <br>
    <br>
    <br>
    <a href="{% url 'publish:index' %}">返回</a>
</div>

{% endblock%}

end/demo001/bookdemo/templates/polls/index.html
{% extends 'polls/base.html'%}

{% block title %}
    投票首页
{% endblock%}

{% block body %}
    <div class="content" style="color: blue">
        <h1>投票问题列表</h1>
        <ul>
            {% for q in questions %}
            <li><a href="{% url 'publish:detail' q.id %}"> {{forloop.counter}} . {{q.title}}</a></li>
            {% endfor %}
        </ul>

    </div>
    <div>
        <a href="{% url 'booktest:index' %}"><b>返回主页面</b></a>
    </div>
{% endblock %}

end/demo001/bookdemo/templates/polls/login.html
{% extends 'polls/base.html' %}

{% block title %}
登录
{% endblock%}
{% block body%}
<div >

    <form action="" method="post">
        {% csrf_token %}
        {% comment %}
        用户名：<input type="text" name="username" required>
        <br>
        密码： <input type="password" name="password" required>
        <br>
        {% endcomment %}


        {{lf.username.label}}:   {{lf.username}}
        <br>
        {{lf.password.label}}:   {{lf.password}}
        <br>

        <input type="submit" value="登录">
        {{ errors }}
    </form>
</div>
<a href="{% url 'publish:index' %}"><b>返回</b></a>
{% endblock%}

end/demo001/bookdemo/templates/polls/regist.html
{% extends 'polls/base.html' %}
{% block title %}
注册
{% endblock%}
{% block body%}
<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        {% comment %}
        用户名：<input type="text" name="username" required>
        <br>
        密码： <input type="password" name="password" required>
        <br>
        重复密码：<input type="password" name="password2" required>
        <br>
        {% endcomment %}

        {{rf.username.label}}:   {{rf.username}}
        <br>
        {{rf.password.label}}:   {{rf.password}}
        <br>
        {{rf.password2.label}}:   {{rf.password2}}
        <br>

        <input type="submit" value="注册">
        {{ errors}}
    </form>
    <a href="{% url 'publish:index' %}">返回</a>
</div>

{% endblock%}

end/demo001/bookdemo/templates/polls/result.html
{% extends 'polls/base.html'%}
{% block title %}
   投票结果
{% endblock%}

{% block body %}
     <div  class="container">
         <h2>问题是: {{question.title}}</h2>

        <ul>
            <h3>得票情况</h3>
            {% for c in question.choices.all %}
                <li>{{c.content}}   {{c.votes}} 票</li>
            {% endfor %}
        </ul>

        <a href="{% url 'publish:index' %}">返回</a>



    </div>


{% endblock%}