end/demo002/blog/apps/blogapp/urls.py
# ProjectName:Ldemo002
# FileName:urls
# author:asus
# datetime:2020/2/20 9:28

from django.conf.urls import url
from . import views
from .feed import *
app_name = 'blogapp'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
    url(r'^favicon.ico/$',views.favicon),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^rss/$',ArticleFeed(), name="rss"),
    url(r'^allblog/$', views.allblog, name='allblog'),

]

end/demo002/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url
from .settings import MEDIA_ROOT
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ueditor/', include('DjangoUeditor.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    path('', include('blogapp.urls', namespace='blogapp'))

]

end/demo002/blog/extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

end/demo002/blog/apps/blogapp/models.py
from django.db import models
from DjangoUeditor.models import UEditorField


# Create your models here.
class Ads(models.Model):
    img = models.ImageField(upload_to='ads', verbose_name='图片')
    desc = models.CharField(max_length=20, null=True, verbose_name='图片描述')

    def __str__(self):
        return self.desc


class Category(models.Model):
    name = models.CharField(max_length=20, verbose_name='分类名')

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=20, verbose_name='标签名')

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=50, verbose_name='文章标题')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='分类')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    update_time = models.DateTimeField(auto_now_add=True, verbose_name='更新时间')
    author = models.CharField(max_length=20, verbose_name='作者')
    # 整数类型 可自加 PositiveIntegerField
    views = models.PositiveIntegerField(default=0, verbose_name='浏览量')
    # body = models.TextField(verbose_name='正文')
    body = UEditorField(imagePath='img/', width='100%', verbose_name='正文')
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title


class Comment(models.Model):
    name = models.CharField(max_length=20, verbose_name='评论人')
    body = models.CharField(max_length=200, verbose_name='评论内容')
    # body = UEditorField(imagePath='img/', width='100%')

    url = models.URLField(default='http://www.cy.com', verbose_name='个人主页')
    email = models.EmailField(default='2388446799@qq.com', verbose_name='个人邮箱')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='评论时间')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name='所属文章')

    def __str__(self):
        return self.name

end/demo002/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        博客实战
        {% endblock%}
    </title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/css/pace.css">
    <link rel="stylesheet" href="/static/css/custom.css">

    <!-- js -->
    <script src="/static/js/jquery-2.1.3.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/pace.min.js"></script>
    <script src="/static/js/modernizr.custom.js"></script>
</head>
<body>
<div id="site-header">
	<div class="container">
		<div class="row">
				<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
								<h1><a href="index.html"><b>博客实战</b></a></h1>
						</div>
				</div><!-- col-md-4 -->
				<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
								<div class="navbar-header">
										<button type="button" id="trigger-overlay" class="navbar-toggle">
												<span class="ion-navicon"></span>
										</button>
								</div>

								<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
										<ul class="nav navbar-nav navbar-right">
												<li class="cl-effect-11"><a href="{% url 'blogapp:index' %}" data-hover="首页">首页</a></li>
												<li class="cl-effect-11"><a href="{% url 'blogapp:allblog' %}" data-hover="博客">博客</a></li>
												<li class="cl-effect-11"><a href="{% url 'blogapp:contact' %}" data-hover="联系">联系</a></li>
										</ul>
								</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
								<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
								<div id="search-form" class="search-form">
										<form role="search" method="get" id="searchform" action="#">
												<input type="search" placeholder="搜索" required>
												<button type="submit"><span class="ion-ios-search-strong"></span></button>
										</form>
								</div>
						</div>
				</div><!-- col-md-8 -->
		</div>
	</div>
</div>
<div class="content-body">
    <div class="container">
        <div class="row">
            {% block main %}

            {% endblock %}

			{% block aside %}

            {% endblock %}

        </div>
    </div>
</div>
<div id="site-footer">
	{% if article %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy {{article.create_time.year}} - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="zzy0371">{{article.author}}</a>
                    - 由<a href="https://github.com/" title="github" target="_blank">{{article.author}}</a>修改
                </p>
            </div>
        </div>
    </div>
	{% else %}
		<div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright" style="color: red;font-family: 宋体;font-size: 24px;align-content: center">
					十分荣幸得以汝之鉴赏
                </p>
            </div>
        </div>
    </div>
	{% endif %}
</div>

<script src="/static/js/script.js"></script>
</body>
</html>

end/demo002/blog/templates/base2.html
{% extends 'base.html' %}
{% load myfun %}
{% block aside %}
    <aside class="col-md-4">
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_latestarticles as latestarticles %}
                    <ul>
                        {% for article in latestarticles %}
                        <li>
                            <a href="{% url 'blogapp:detail' article.id %}">{{ article.title }}</a>
                        </li>
                        {% endfor %}

                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% get_latedates as latedate %}
                    <ul>
                        {% for dates in latedate %}
                            <li>
                                <a href="/?type=date&year={{dates.year}}&month={{dates.month}}">{{dates.year}} 年 {{dates.month}} 月</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_latecategory as latecategory %}
                    <ul>
                        {% for cate in latecategory %}
                        <li>
                            <a href="/?type=category&category_id={{cate.id}}">{{cate.name}} <span class="post-count">({{cate.article_set.count}})</span></a>
                        </li>
                        {% endfor%}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_taps as taps %}
                    <ul>
                        {% for tag in taps %}
                        <li>
                            <a href="/?type=tag&tag_id={{tag.id}}">{{tag.name}}</a>
                        </li>

                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'blogapp:rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
{% endblock %}

end/demo002/blog/templates/contact.html
{% extends 'base.html' %}
{% block title %}
    博客实战首页
{% endblock %}

{% block main %}
	<main class="col-md-12">
            	<h1 class="page-title">Contact</h1>
            	<article class="post">
            		<div class="entry-content clearfix">
            			<form action="#" method="post" class="contact-form">
            				<div class="row">
            					<div class="col-md-6 col-md-offset-3">
            						<input type="text" name="name" placeholder="名字" required>
            						<input type="email" name="email" placeholder="邮箱" required>
            						<textarea name="message" rows="7" placeholder="建议" required></textarea>
            						<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>发送</span></button>
            					</div>
            				</div>	<!-- row -->
            			</form>
            		</div>
            	</article>
            </main>
{% endblock %}

end/demo002/blog/templates/full-width.html
{% extends 'base.html'  %}
{% block title %}
全部博客
{% endblock %}

{% block main %}
<main class="col-md-12">
    <article class="post post-1">

        <div class="entry-content clearfix">

            {% for a in articles %}

            <h1>
                <a href="{% url 'blogapp:detail' a.id %}">{{a.title}}</a>
            </h1>

            {% endfor %}


        </div>
    </article>
    <!-- 简单分页效果
    <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
    </div>
    -->
    <div class="pagination col-md-11">
        <ul>
            {% if page.has_previous %}
            <li class="col-md-2"><a
                    href="?pagenum={{page.previous_page_number}}&type={{typepage}}&year={{year}}&month={{month}}&category_id={{category_id}}&tag_id={{tag_id}}">上一页</a>
            </li>
            {% endif %}

            {% for peg in page.paginator.page_range %}
            {% if peg == page.number %}

            <li class="current col-md-1"><a
                    href="?pagenum={{peg}}&type={{typepage}}&year={{year}}&month={{month}}&category_id={{category_id}}&tag_id={{tag_id}}">{{peg}}</a>
            </li>
            {% else %}
            <li class="col-md-1"><a
                    href="?pagenum={{peg}}&type={{typepage}}&year={{year}}&month={{month}}&category_id={{category_id}}&tag_id={{tag_id}}">{{peg}}</a>
            </li>
            {% endif %}

            {% endfor %}

            {% if page.has_next %}
            <li class="col-md-2"><a
                    href="?pagenum={{ page.next_page_number}}&type={{typepage}}&year={{year}}&month={{month}}&category_id={{category_id}}&tag_id={{tag_id}}">下一页</a>
            </li>
            {% endif %}
        </ul>
    </div>
</main>

{% endblock %}

end/demo002/blog/templates/index.html
{% extends 'base2.html' %}

{% load myfun %}
{% block title %}
博客实战首页
{% endblock %}

{% block main %}
<main class="col-md-8">

    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">

            {% for a in ads %}
            {% if forloop.counter0 == 0 %}
            <li data-target="#carousel-example-generic" data-slide-to="{{forloop.counter0}}" class="active"></li>
            {% else %}
            <li data-target="#carousel-example-generic" data-slide-to="{{forloop.counter0}}"></li>
            {% endif %}

            {% endfor %}


        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">

            {% for a in ads %}
            {% if forloop.counter0 == 0 %}
            <div class="item active">

                <img src="/media/{{a.img}}" alt="...">
                <div class="carousel-caption">
                    <h1>{{a.desc}}</h1>
                </div>
            </div>
            {% else %}
            <div class="item">
                <img src="/media/{{a.img}}" alt="...">
                <div class="carousel-caption">
                    <h1>{{a.desc}}</h1>
                </div>
            </div>
            {% endif %}

            {% endfor %}


        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    {% for a in page.object_list %}
<!--    {{ a }}-->
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">
                <a href="{% url 'blogapp:detail' a.id %}">{{a.title}}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#"> {{a.category.name}}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="2012-11-09T23:15:57+00:00">{{a.create_time|date:'Y年m月d日'}}</time></a></span>
                <span class="post-author"><a href="#">{{a.author|authorFormat:'作者'}}</a></span>
                <span class="comments-link"><a href="#">{{ a.comment_set.count}} 评论</a></span>
                <span class="views-count"><a href="#">{{a.views}} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            <p>{{a.body|safe|truncatechars_html:20}}</p>
            <div class="read-more cl-effect-14">
                <a href="{% url 'blogapp:detail' a.id %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
            </div>
        </div>
    </article>
    {% endfor %}

    <!-- 简单分页效果
    <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
    </div>
    -->
    <div class="pagination col-md-11">
        <ul>
            {% if page.has_previous %}
            <li class="col-md-2"><a href="?pagenum={{page.previous_page_number}}&type={{typepage}}&year={{year}}&month={{month}}&category_id={{category_id}}&tag_id={{tag_id}}">上一页</a></li>
            {% endif %}

            {% for peg in page.paginator.page_range %}
                {% if peg == page.number %}

                    <li class="current col-md-1"><a href="?pagenum={{peg}}&type={{typepage}}&year={{year}}&month={{month}}&category_id={{category_id}}&tag_id={{tag_id}}">{{peg}}</a></li>
                {% else %}
                    <li class="col-md-1"><a href="?pagenum={{peg}}&type={{typepage}}&year={{year}}&month={{month}}&category_id={{category_id}}&tag_id={{tag_id}}">{{peg}}</a></li>
                {% endif %}

            {% endfor %}

            {% if page.has_next %}
                <li class="col-md-2"><a href="?pagenum={{ page.next_page_number}}&type={{typepage}}&year={{year}}&month={{month}}&category_id={{category_id}}&tag_id={{tag_id}}">下一页</a></li>
            {% endif %}
        </ul>
    </div>
</main>
{% endblock %}

end/demo002/blog/templates/single.html
{% extends 'base2.html' %}
{% load myfun %}
{% block title %}
博客实战文章
{% endblock %}

{% block main %}
<main class="col-md-8">

    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">{{article.title}}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#"> {{article.category_set.name}}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="2012-11-09T23:15:57+00:00">{{article.create_time|date:'Y年m月d日'}}</time></a></span>
                <span class="post-author"><a href="#">{{article.author|authorFormat:'作者'}}</a></span>
                <span class="comments-link"><a href="#">{{article.comment_set.count}} 评论</a></span>
                <span class="views-count"><a href="#">{{article.views}} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
           {{article.body|safe}}
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="#" method="post" class="comment-form">
            {% csrf_token %}
            {% comment %}
            <div class="row">
                <div class="col-md-4">
                    <label for="id_name">名字：</label>
                    <input type="text" id="id_name" name="name" required>
                </div>
                <div class="col-md-4">
                    <label for="id_email">邮箱：</label>
                    <input type="email" id="id_email" name="email" required>
                </div>
                <div class="col-md-4">
                    <label for="id_url">网址：</label>
                    <input type="text" id="id_url" name="url">
                </div>
                <div class="col-md-12">
                    <label for="id_comment">评论：</label>
                    <textarea name="comment" id="id_comment" required></textarea>
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>
            {% endcomment %}


            <div class="col-md-4">
                <label for="{{cf.name.id_for_label}}">{{cf.name.label}}</label>
                    {{cf.name}}
            </div>
            <div class="col-md-4">
               <label for="{{cf.email.id_for_label}}">{{cf.email.label}}</label>
                    {{cf.email}}
            </div>
            <div class="col-md-4">
                <label for="{{cf.name.id_for_label}}">{{cf.url.label}}</label>
                    {{cf.url}}
            </div>
            <div class="col-md-12">
                <label for="{{cf.body.id_for_label}}">{{cf.body.label}}</label>
                    {{cf.body|safe}}
                <button type="submit" class="comment-btn">发表</button>
            </div>

            <!-- row -->
        </form>
        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{article.comment_set.count}}</span> 条评论</h3>

            <ul class="comment-list list-unstyled">
                {% for c in article.comment_set.all %}
                <li class="comment-item">
                    <span class="nickname">{{c.name}}</span>
                    <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{c.create_time|date:'Y年m月d日'}}</time>
                    <div class="text">
                        {{c.body|safe}}
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </section>


</main>
{% endblock %}