end/demo001/bookdemo/bookdemo/urls.py
from django.contrib import admin
from django.urls import path, include

'''
路由地址配置
每一个网址绑定一个视图函数，视图函数返回页面
MVT T视图 作用： 接受请求  处理数据 返回响应
总的路由配置文件 == 项目路由文件 使用include包含
'''

urlpatterns = [
    path('admin/', admin.site.urls),
    path('publish/', include('publish.urls', namespace='publish')),
    path('', include('booktest.urls', namespace='booktest')),


]

end/demo001/bookdemo/booktest/urls.py
# ProjectName:Ldemo001
# FileName:urls
# author:asus
# datetime:2020/2/13 14:36
# software: PyCharm
"""
引入绑定路由
"""
from django.conf.urls import url

from . import views

app_name = "booktest"
urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^list/$', views.list, name='list'),
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
    url(r'^deletebook/(\d+)/$', views.deletebook, name='deletebook'),
    url(r'^deletehero/(\d+)/$', views.deletehero, name='deletehero'),
    url(r'^addhero/(\d+)/$', views.addhero, name='addhero'),
    url(r'^edithero/(\d+)/$', views.edithero, name='edithero'),
    url(r'^editbook/(\d+)/$', views.editbook, name='editbook'),

]

end/demo001/bookdemo/publish/urls.py
# ProjectName:Ldemo001
# FileName:urls
# author:asus
# datetime:2020/2/17 10:14
# software: PyCharm
from django.conf.urls import url
from . import views

app_name = 'publish'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # url(r'^detail/(\d+)/$', views.detail, name='detail'),

    url(r'^detail/(?P<qid>\d+)/$', views.detail, name='detail'),
    url(r'^result/(\d+)/$', views.result, name='result'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^regist/$', views.regist, name='regist')

    # url(r'^$',views.IndexView.as_view(),name='index'),
    # url(r'^detail/(?P<qid>\d+)/$',views.DetailView.as_view(),name='detail'),
    # url(r'^result/(\d+)/$',views.ResultView.as_view(),name='result')

]

end/demo001/bookdemo/templates/addhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<body>
    <div>
       <form action="#" method="post">
           姓名：<input type="text" name="heroname" value="{{hero.name}}">
           <br>
           性别：<input type="radio" name="sex" value="female" checked> 女 <input type="radio" name="sex" value="male" > 男
           <br>
           技能：<input type="text" name="content" value="{{hero.content}}">
           <br>
           <input type="submit" value="提交">
       </form>

    </div>

</body>





</html>

end/demo001/bookdemo/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
<h1>书籍详情</h1>
<h2>{{ book.title }}</h2>
<div>

    <ul>
        {% for hero in book.heros.all %}
        <li>
            <p>
                {{ hero.book }} -- {{ hero.content }} -- {{ hero.gender }} -- {{ hero.name }}
                <a href="{% url 'booktest:edithero' hero.id %}" style="color: black">编辑</a>
                <a href="{% url 'booktest:deletehero' hero.id %}" style="color: red">删除</a>
            </p>
        </li>
        {% endfor %}

    </ul>

    <a href="{% url 'booktest:addhero' book.id %}">添加</a>
</div>
<div>
<!--    <video src="/static/resource/张芸京 - 偏爱.mp4" controls style="width: 500px;"></video>-->
</div>
{# <a href="/">返回列表</a> #}
<a href="{% url 'booktest:index' %}">返回列表</a>


</body>
</html>

end/demo001/bookdemo/templates/editbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>书籍编辑</title>

</head>
<body>
    <form action="#" method="post">
        书籍名字：<input type="text" name="booktitle" value="{{book.title}}">
        <br>
        书籍价格：<input type="number" name="price" value="{{book.price}}">
        <br>
        书籍日期：<input type="date" name="update" value="{{book.pub_date}}">
        <br>
        <input type="submit" value="提交">
    </form>



</body>
</html>

end/demo001/bookdemo/templates/edithero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>英雄编辑</title>
    <link rel="stylesheet" href="/static/css/main.css">

</head>
<body>
<div>
    <form action="#" method="post">
        姓名：<input type="text" name="heroname" value="{{hero.name}}">
        <br>

        技能：<input type="text" name="content" value="{{hero.content}}">
        <br>

        {% if hero.gender == 'female' %}
        性别：<input type="radio" name="sex" value="female" checked> 女 <input type="radio" name="sex" value="male"> 男
        {% else %}
        性别：<input type="radio" name="sex" value="female"> 女 <input type="radio" name="sex" value="male" checked> 男
        {% endif %}
        <br>
        <input type="submit" value="提交">
    </form>


</div>

</body>
</html>

end/demo001/bookdemo/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" href="/static/css/main.css">

</head>
<body >
    <div style="text-align: center;text-decoration: none">


           <h1>首页欢迎</h1>
    <br>
    <a href="{% url 'publish:index' %}" style="text-decoration:underline red"><h2 style="color: red;">投票页面</h2></a>
    <br>
    <div class="content" >
        <h2>所有书籍</h2>

        <p><b>查看详情请点击书名</b></p>
        <br>
        <ul style="margin-left: 10px">
            {% for book in books %}
            {# <a href="/booktest/detail/{{book.id}}"> <li>{{ book }}</li> </a> #}


            <li>
                <a href="{% url 'booktest:detail' book.id %}"> {{ book }} ---- {{book.price}} ---- {{book.pub_date}}</a>

                <a href="{% url 'booktest:editbook' book.id %}" style="color: black">编辑</a>

                <a href="{% url 'booktest:deletebook' book.id %}" style="color: red">删除</a>
            </li>

            {% endfor %}
        </ul>
    </div>


    <div class="pict">
<!--        <iframe src="/static/img/afc.jpg" frameborder="0"></iframe>-->
        <img src="/static/img/afc.jpg" alt="" style="width: 300px;height: 170px">

    </div>
     <div>
        <audio src="/static/resource/山鬼.mp3" controls style="width: 300px;"></audio>
    </div>

    </div>

</body>
</html>